###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "admin",
    "password": "hieudz"
}

###
GET http://localhost:3000/api/todays
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwicGFzc3dvcmQiOiJoaWV1ZHoiLCJpYXQiOjE2ODA4ODcxNDYsImV4cCI6MTY4MDg5MDc0Nn0.bEknN2TdnXECwOz6x79xdooBqGxyCVo2Kmkd5CjqcAE